include:
    - HueBulb_acl.yml
    - WeMoSwitch_acl.yml

vlans:
    office:
        vid: 100
        description: "office network"

acls:
    enable_dhcp:
        - rule:
            dl_type: 0x800
            nw_proto: 17
            tcp_src: 68
            tcp_dst: 67
            actions:
                allow: 1
                output:
                    port: 2
        - rule:
            dl_type: 0x86dd     # ipv6
            nw_proto: 17        # udp
            udp_src: 547        # dhcpv6-server
            udp_dst: 546        # dhcpv6-client
            actions:
                allow: 1
                output:
                    port: 2
        - rule:
            dl_type: 0x0806     # ARP Packets
            actions:
                allow: 1
        - rule:
            eth_type: 2048
            ip_proto: 6
            ipv4_dst: 10.0.0.2
            actions:
                allow: 1
        - rule:
            actions:
                allow: 0
    enable_incoming:
        - rule:
            dl_type: 0x800
            ipv4_dst: 10.0.0.2
            actions:
                allow: 1
        - rule:
            actions:
                allow: 0
    disable_all_and_forward:
        - rule:
            actions:
                allow: 0
                mirror: 3
    disable_all:
        - rule:
            actions:
                allow: 0
    enable_dns:
        - rule:
            dl_type: 0x800
            nw_proto: 17
            tcp_src: 68
            tcp_dst: 67
            actions:
                allow: 1
                output:
                    port: 2
        - rule:
            dl_type: 0x0806     # ARP Packets
            actions:
                allow: 1
                output:
                    port: 2
        - rule:
            dl_type: 0x800
            nw_dst: "10.0.0.2"
            actions:
                allow: 1
        - rule:
            dl_type: 0x800
            nw_dst: "8.8.8.8"
            actions:
                allow: 1
                output:
                    port: 2

        - rule:
            dl_type: 0x800
            nw_dst: "192.168.1.1"
            actions:
                allow: 1
                output:
                    port: 2
        - rule:
            dl_type: 0x800
            ipv4_src: "192.168.1.1"
            ipv4_dst: "10.0.0.1"
            actions:
                allow: 1
                output:
                    port: 2
        - rule:
            dl_type: 0x800
            ipv4_src: "8.8.8.8"
            ipv4_dst: "10.0.0.1"
            actions:
                allow: 1
                output:
                    port: 2
        - rule:
              dl_type: 0x800
              nw_dst: "8.8.4.4"
              actions:
                  allow: 1
                  output:
                      port: 2
        - rule:
              dl_type: 0x800
              ipv4_src: "8.8.4.4"
              ipv4_dst: "10.0.0.1"
              actions:
                  allow: 1
                  output:
                      port: 2
        - rule:
              dl_type: 0x800
              nw_dst: "10.10.10.1"
              actions:
                  allow: 1
                  output:
                      port: 2
        - rule:
              dl_type: 0x800
              ipv4_src: "10.10.10.1"
              ipv4_dst: "10.0.0.1"
              actions:
                  allow: 1
                  output:
                      port: 2
    enable_incoming_disable_outcoming:
        - rule:
            dl_type: 0x800
            nw_dst: "10.0.0.1"
            actions:
                allow: 1
        - rule:
            dl_type: 0x800
            nw_src: "10.0.0.1"
            actions:
                allow: 0
    allow-all:
        - rule:
            actions:
                allow: 1

dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            1:
                name: "h1"
                description: "host1 network namespace"
                native_vlan: office
                acls_in: [enable_dns, hubbulb_rule, wemoswitch_rule, enable_incoming_disable_outcoming]
            2:
                name: "h2"
                description: "host2 network namespace"
                native_vlan: office
            3:
                name: "nat0"
                description: "nat0 network interfaces"
                native_vlan: office
